### ISSUE TITLE
Daň_z_nemovitosti

### ISSUE THREAD

**Issue by hanca1605** [hanca1605/CZECHITAS_PYTHON-DLOUHODOB-#1]
@pesikj , Prosím o potvrzení, že vidíš úkol a že je vše OK. Děkuji H.

**Comment by pesikj** [comment]
Ahoj @hanca1605, úkol je zpracovaný moc hezky, líbí se mi vyvolání výjimky, s tím jsi napřed oproti kurzu :-) Pouze bych doporučil dávat importy úplně nahoru na začátek programu před kód, je to tak běžné a používá se to tak kvůli přehlednosti.
